const POSTS = [
  {
    id: 'post1',
    cover: '/assets/images/covers/cover_1.jpg',
    title: 'Introduction to Video Streaming Architecture',
    createdAt: new Date(Date.now() - 3 * 86400000),
    view: 24135,
    comment: 42,
    share: 18,
    favorite: 112,
    author: { name: 'Alice Johnson', avatarUrl: '/assets/images/avatars/avatar_1.jpg' },
  },
  {
    id: 'post2',
    cover: '/assets/images/covers/cover_2.jpg',
    title: 'Understanding HLS and Video Transcoding',
    createdAt: new Date(Date.now() - 8 * 86400000),
    view: 18220,
    comment: 29,
    share: 11,
    favorite: 89,
    author: { name: 'Bob Smith', avatarUrl: '/assets/images/avatars/avatar_2.jpg' },
  },
  {
    id: 'post3',
    cover: '/assets/images/covers/cover_3.jpg',
    title: 'Optimizing Video Uploads with BullMQ',
    createdAt: new Date(Date.now() - 15 * 86400000),
    view: 32100,
    comment: 77,
    share: 44,
    favorite: 230,
    author: { name: 'Carol Davis', avatarUrl: '/assets/images/avatars/avatar_3.jpg' },
  },
  {
    id: 'post4',
    cover: '/assets/images/covers/cover_4.jpg',
    title: 'MERN Stack Best Practices',
    createdAt: new Date(Date.now() - 25 * 86400000),
    view: 45600,
    comment: 103,
    share: 67,
    favorite: 389,
    author: { name: 'David Wilson', avatarUrl: '/assets/images/avatars/avatar_4.jpg' },
  },
  {
    id: 'post5',
    cover: '/assets/images/covers/cover_5.jpg',
    title: 'Scaling Video Processing with Redis Queues',
    createdAt: new Date(Date.now() - 40 * 86400000),
    view: 15010,
    comment: 19,
    share: 9,
    favorite: 54,
    author: { name: 'Eva Martinez', avatarUrl: '/assets/images/avatars/avatar_5.jpg' },
  },
];

export default POSTS;
